---

- name: Restrict to specifc groups
  when: item.inventory_groups is undefined or group_names | intersect(item.inventory_groups) | length > 0
  block:

    - name: Delete all obsolete users (Windows)
      ansible.windows.win_user:
        name: "{{ item.name }}"
        state: absent
      loop: "{{ users_rm }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Delete obsolete groups (Windows)
      ansible.windows.win_group:
        name: "{{ item.name }}"
        state: absent
      loop: "{{ grps_rm }}"
      loop_control:
        label: "{{ item.name }}"
