---

- name: Restrict to specifc groups
  when: item.inventory_groups is undefined or group_names | intersect(item.inventory_groups) | length > 0
  block:

    - name: Create all groups
      ansible.windows.win_group:
        state: present
        name: "{{ item.name }}"
      loop: "{{ grps }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Create all users
      ansible.windows.win_user:
        name: "{{ item.name }}"
        state: present
        account_disabled: "{{ item.account_disabled | default(omit) }}"
        account_locked: "{{ item.account_locked | default(omit) }}"
        description: "{{ item.description | default(omit) }}"
        fullname: "{{ item.fullname | default(omit) }}"
        groups: "{{ item.groups | default(omit) }}"
        groups_action: "{{ item.groups_action | default(omit) }}"
        home_directory: "{{ item.home_directory | default(omit) }}"
        login_script: "{{ item.login_script | default(omit) }}"
        password: "{{ item.password | default(omit) }}"
        password_expired: "{{ item.password_exired | default(False) }}"
        password_never_expires: "{{ item.password_never_expires | default(omit) }}"
        profile: "{{ item.profile | default(omit) }}"
        update_password: "{{ item.update_password | default('on_create') }}"
        user_cannot_change_password: "{{ item.user_cannot_change_password | default(omit) }}"
      loop: "{{ users }}"
      loop_control:
        label: "{{ item.name }}"
